### ISSUE TITLE
Can't render within component

### ISSUE THREAD

**Issue by thejase** [davidtheclark/react-aria-modal#22]
Is there a way to displace this modal within my app instead of a DOM element outside of the app?  Essentially, I would like it to be displaced within my component so I can use `position: absolute` to takeover the component.

**Comment by davidtheclark** [comment]
@thejase There is not right now. Can you say more about what you want, though, because it sounds dubious to me. The main features of this component are that it traps focus, freezes scroll on the body, and appends the element at the bottom of the body instead of directly inline. It sounds like for your use-case you don't actually want *any* of these features, right? If that's the case, maybe you don't want to use this component?

**Comment by thejase** [comment]
So I would prefer a trap on the modal. I'd just like it to only overlay on the content (not the site header), and allow manual untrapping via mouse (or other virtual input) on the header. In other words, the header and its menu should still function as an escape or change of flow. 

That said, now that I think about it, that's arguably a non-modal dialog, so maybe this isn't the right place for this. 

You're right, however,

**Comment by davidtheclark** [comment]
@thejase Yeah, I think I understand what you're going for, but I think it might require too many changes to this component — and you'd be better off using the building-block modules to put together a new component.
