### ISSUE TITLE
Modal does not close when clicking the overlay

### ISSUE THREAD

**Issue by joeswick999** [davidtheclark/react-aria-modal#85]
Modal will not close when clicking the overlay.

https://codesandbox.io/s/kmlr5z5n4o

**Comment by rsnay** [comment]
This appears to be because the #root div element into which the main react component is being rendered has a height of 0, and so no click events are getting captured. Making the root div element fill half of the screen allows the modal to be closed by clicking the overlay in that half of the screen. Updated demo: https://codesandbox.io/s/545v289mwl

**Comment by joeswick999** [comment]
You are right, thank you so much.
